### ISSUE TITLE
Attention tu as laissé un token dans le code

### ISSUE THREAD

**Issue by pierreminiggio** [Listeriaa/endangered-french-species#1]
Les tokens ne devraient pas êtres envoyés sur GitHub, généralement on les mets dans fichier qui est ignoré (via le .gitignore).
Là actuellement, n'importe qui va pouvoir utiliser tes accès à l'API.

https://github.com/Listeriaa/endangered-french-species/blob/3f9204bee1df40d7c95876bae87d5d84f3b95da2/app.js#L2

Je viens de lire dans ton README.md que tu vas sûrement passer cette App en React.
Dans React tu as le [package dotenv](https://www.npmjs.com/package/dotenv) qui est déjà intégré et qui te permet de faire ça via un fichier .env.local

**Comment by Listeriaa** [comment]
Merci Pierre, je vais gérer ça pour bien sécuriser le repo.

**Comment by thib3113** [comment]
@Listeriaa je me permets d'en rajouter une couche, mais : 
- le token est en fait toujours visible dans github ( juste en cliquant sur le lien du message de pierre par exemple ) . Je te conseille de passer un coup de l'outil [BFG](https://rtyley.github.io/bfg-repo-cleaner/) sur ton repo
- vue le fonctionnement de ton application, tu vas forcément avoir un problème de token ... la seule façon de sécuriser cela serait de migrer la récupération des données coté back end de l'app. ( actuellement, le token est toujours visible dans le js, et même quand tu appelles l'api ) . 

Et, à moins que l'api limite l'utilisation du token à certains domaines (mais bizarre qu'ils acceptent github.io dans ce cas), tu laisses libre accès au token à d'autres personnes (et ça veut dire que tu deviens responsable des appels que les autres personnes font avec / et que ces autres personnes peuvent avoir un token à utiliser à des fins malveillantes, qui irait à l'inverse de ton projet) 

Et malheureusement, à titre personnel, je pense qu'il vaut mieux ne pas faire de projet, qu'un projet permettant de faire du mal à ce genre de sites (quand un petit PHP qui génère un fichier json de cache suffirait largement pour l'usage)
